### ISSUE TITLE
Mod not found

### ISSUE THREAD

**Issue by BluePixel1708** [teamauroramods/BayouBlues-Fabric#2] opened 2021-07-07 04:40 UTC
I installed the mod, made sure it was fabric and ran the game.
However the mod doesn't appear on mod menu, nor do any of the content appear in the world, which was a new world
I searched up on REI, used /locatebiome and searched through creative inventory and didn't find anything related to the mod.

**Comment by ex0planetary** [comment] 2021-07-07 05:09
duplicate of #1

**Closed as completed by ex0planetary** 2021-07-07 05:09 UTC
